begin;

-- =========================================================
-- PHASE 2 - ECONOMY CENTRALIZATION (1/3): CENTRAL CONFIG +
-- 3-TIER ROUND PLACEMENT REWARDS
--
-- WHY
-- The human-approved economy baseline (Phase 2 directive) makes
-- three corrections to what Phase 1 shipped:
--
--   1. Match DP was Win 100 / Draw 75 / Loss 50. Approved baseline
--      is Win 100 / Loss 75 (Draw already happened to be 75, so it
--      is unchanged). This was hardcoded as three integer literals
--      inside _compute_league_match_reward - no config table
--      existed for match DP at all.
--
--   2. Round rewards only had two roles (participation, round_winner
--      - corrected to 250 DP+1 Premium Pack / 150 DP+1 Standard Pack
--      by 202608310000_round_reward_economy_correction.sql). The
--      real approved baseline has THREE placement tiers within a
--      round: 1st +150 DP+1 Standard Pack, 2nd +75 DP (no pack), 3rd
--      no additional placement bonus - on top of a universal 250
--      DP+1 Premium Pack "round completion" reward for every
--      competition player, not just the two who happened to have a
--      match that specific round_number.
--
--      generate_round_robin_matches_v2 pads an odd player count
--      (the real league is 3 players) with one synthetic null "bye"
--      slot, and silently drops any match pairing that involves it -
--      so for 3 players, every round_number has exactly ONE real
--      match, and the sitting-out player is never recorded as a
--      "bye" anywhere in the schema. The old settle_round_rewards_v2
--      only paid "participation" to the two players who appeared in
--      that round's match rows, which meant the bye player got
--      NOTHING for a round they structurally could not play in - the
--      opposite of the approved design ("repeated losing should NOT
--      make a player unable to participate in the economy", and
--      Phase 2's own round-payout example table gives all three
--      placements the same 250 Round DP). This migration fixes that:
--      participation is now granted to every public.competition_
--      players row for the competition, independent of whether they
--      have a match in that specific round_number. The match winner
--      of that round is "1st" (role round_winner, unchanged name for
--      backward compatibility with existing grant rows). The match
--      loser of that round is "2nd" (new role round_runner_up). A
--      player with no match that round (the bye) is "3rd" - they
--      simply never qualify for round_winner or round_runner_up,
--      which already IS "no additional placement bonus" - no new
--      code path needed for that case specifically.
--
--      This generalizes cleanly to a hypothetical >3-player
--      competition too (multiple simultaneous matches per round):
--      every match's winner is a round_winner, every match's loser
--      is a round_runner_up, anyone with no match that round is
--      participation-only. This is an intentional, minimal
--      generalization of the existing "a round is however
--      generate_round_robin_matches_v2 grouped matches by
--      round_number" model - not a new design decision.
--
--   3. No single place said what these values ARE for future
--      competitions - both fixes lived only as literals baked into
--      function bodies (_compute_league_match_reward) or as a
--      one-time INSERT (install_default_round_rewards_v2). This
--      migration adds one small singleton table,
--      league_economy_defaults, as the actual single source of
--      truth for match DP and round-reward defaults: change future
--      behavior with one UPDATE to that single row, no code
--      deploy required. (Pack prices already have their own
--      pre-existing authoritative config - shop_pack_types - so they
--      are NOT duplicated here; see 202608311200's header.)
--
-- SAFE TO RE-RUN
-- The singleton insert is ON CONFLICT DO NOTHING. The check-
-- constraint changes use a DO block that finds and drops whatever
-- the existing role/reward_role check constraint is actually named
-- (rather than guessing the autogenerated name) before adding the
-- new one - safe to run again since the second run's DROP is a
-- clean no-op (the constraint it looks for, matching the OLD
-- definition, will already be gone) and ADD CONSTRAINT IF NOT
-- EXISTS-equivalent is achieved by checking existence first. Every
-- other statement is a plain CREATE OR REPLACE FUNCTION or an
-- ON CONFLICT-guarded INSERT.
-- =========================================================


-- ---------------------------------------------------------
-- 1. league_economy_defaults - singleton central config for
--    match DP + round-reward defaults.
-- ---------------------------------------------------------

create table if not exists public.league_economy_defaults (
  id boolean primary key default true check (id),

  match_win_dp integer not null default 100 check (match_win_dp >= 0),
  match_draw_dp integer not null default 75 check (match_draw_dp >= 0),
  match_loss_dp integer not null default 75 check (match_loss_dp >= 0),

  round_participation_dp integer not null default 250
    check (round_participation_dp >= 0),
  round_participation_voucher_type text not null default 'premium_pack'
    check (round_participation_voucher_type in ('normal_pack', 'premium_pack', 'deluxe_pack', 'special_pack')),
  round_participation_voucher_quantity integer not null default 1
    check (round_participation_voucher_quantity >= 0),

  round_first_dp integer not null default 150 check (round_first_dp >= 0),
  round_first_voucher_type text not null default 'normal_pack'
    check (round_first_voucher_type in ('normal_pack', 'premium_pack', 'deluxe_pack', 'special_pack')),
  round_first_voucher_quantity integer not null default 1
    check (round_first_voucher_quantity >= 0),

  round_second_dp integer not null default 75 check (round_second_dp >= 0),

  updated_at timestamptz not null default now()
);

comment on table public.league_economy_defaults is
  'Singleton (one row, id is always true) source of truth for match-DP and round-reward defaults - see this migration''s header for why. install_default_round_rewards_v2() seeds a competition''s own competition_round_reward_rules from this row at competition-start time; _compute_league_match_reward() reads match_* directly on every match settlement. A competition''s already-installed rules are a per-competition override copy (same pattern competition_reward_rules already used) - updating this singleton changes the default for competitions started AFTER the update, not retroactively; re-apply install_default_round_rewards_v2 manually (it is ON CONFLICT DO NOTHING, so delete the old rule rows first) to push a change onto an existing competition. Pack shop prices are NOT here - shop_pack_types is already the pre-existing, live-read authoritative config for those, see 202608311200''s header.';

insert into public.league_economy_defaults (id)
values (true)
on conflict (id) do nothing;

alter table public.league_economy_defaults enable row level security;

drop policy if exists league_economy_defaults_select_authenticated on public.league_economy_defaults;
create policy league_economy_defaults_select_authenticated on public.league_economy_defaults
  for select to authenticated
  using (true);

revoke insert, update, delete on public.league_economy_defaults from authenticated;
grant select on public.league_economy_defaults to authenticated;


-- ---------------------------------------------------------
-- 2. _compute_league_match_reward - now reads match_win_dp /
--    match_draw_dp / match_loss_dp from league_economy_defaults
--    instead of hardcoded literals. Changed from IMMUTABLE to
--    STABLE (it now reads a table) - this is still correct: its
--    result only needs to be constant within a single statement/
--    transaction, never across transactions, and it is only ever
--    called from within other functions' own transactions, never
--    from an index or generated column.
-- ---------------------------------------------------------

create or replace function public._compute_league_match_reward(
  winner_id uuid,
  player_id uuid,
  other_player_id uuid
)
returns integer
language sql
stable
set search_path to 'public'
as $function$
  select case
    when winner_id is null then d.match_draw_dp
    when winner_id = player_id then d.match_win_dp
    when winner_id = other_player_id then d.match_loss_dp
    else null -- an invalid winner_id (neither player) - caller must handle
  end
  from public.league_economy_defaults d
  where d.id = true;
$function$;

revoke all on function public._compute_league_match_reward(uuid, uuid, uuid) from public;
-- No grant at all - pure internal helper, only ever called from
-- other SECURITY DEFINER functions in this same schema (unchanged
-- from the prior version).


-- ---------------------------------------------------------
-- 3. Widen the role / reward_role check constraints to add the new
--    'round_runner_up' tier (2nd place). Looked up dynamically
--    rather than assuming the autogenerated constraint name, so
--    this is safe regardless of exactly how Postgres named the
--    inline CHECK when the tables were first created.
-- ---------------------------------------------------------

do $$
declare
  con record;
begin
  for con in
    select c.conname
    from pg_constraint c
    join pg_class rel on rel.oid = c.conrelid
    where rel.relname = 'competition_round_reward_rules'
      and c.contype = 'c'
      and pg_get_constraintdef(c.oid) ilike '%role%'
  loop
    execute format('alter table public.competition_round_reward_rules drop constraint %I', con.conname);
  end loop;
end;
$$;

alter table public.competition_round_reward_rules
  add constraint competition_round_reward_rules_role_check
  check (role in ('participation', 'round_winner', 'round_runner_up'));

do $$
declare
  con record;
begin
  for con in
    select c.conname
    from pg_constraint c
    join pg_class rel on rel.oid = c.conrelid
    where rel.relname = 'competition_round_reward_grants'
      and c.contype = 'c'
      and pg_get_constraintdef(c.oid) ilike '%reward_role%'
  loop
    execute format('alter table public.competition_round_reward_grants drop constraint %I', con.conname);
  end loop;
end;
$$;

alter table public.competition_round_reward_grants
  add constraint competition_round_reward_grants_reward_role_check
  check (reward_role in ('participation', 'round_winner', 'round_runner_up'));


-- ---------------------------------------------------------
-- 4. install_default_round_rewards_v2 - now seeds all THREE roles
--    from league_economy_defaults instead of two hardcoded rows.
-- ---------------------------------------------------------

create or replace function public.install_default_round_rewards_v2(
  target_competition_id uuid
)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  d public.league_economy_defaults%rowtype;
begin
  select * into d from public.league_economy_defaults where id = true;

  if not found then
    -- Defensive fallback matching this migration's own seeded
    -- defaults - should be unreachable, since section 1 above
    -- always inserts the singleton row first.
    d.round_participation_dp := 250;
    d.round_participation_voucher_type := 'premium_pack';
    d.round_participation_voucher_quantity := 1;
    d.round_first_dp := 150;
    d.round_first_voucher_type := 'normal_pack';
    d.round_first_voucher_quantity := 1;
    d.round_second_dp := 75;
  end if;

  insert into public.competition_round_reward_rules (
    competition_id, role, duel_points, voucher_type, voucher_quantity
  ) values
    (target_competition_id, 'participation', d.round_participation_dp, d.round_participation_voucher_type, d.round_participation_voucher_quantity),
    (target_competition_id, 'round_winner', d.round_first_dp, d.round_first_voucher_type, d.round_first_voucher_quantity),
    (target_competition_id, 'round_runner_up', d.round_second_dp, null, 0)
  on conflict (competition_id, role) do nothing;
end;
$function$;

revoke all on function public.install_default_round_rewards_v2(uuid) from public;
grant execute on function public.install_default_round_rewards_v2(uuid) to authenticated;

-- Backfill: any competition that already has round reward rules
-- installed (from Phase 1 onward) has 'participation'/'round_winner'
-- but is missing the new 'round_runner_up' tier entirely - add it
-- using the same defaults, without touching the existing two rows
-- (their Phase-1-corrected values - 250/premium_pack/1 and
-- 150/normal_pack/1 - already match the approved baseline exactly,
-- so there is nothing to correct there).
insert into public.competition_round_reward_rules (
  competition_id, role, duel_points, voucher_type, voucher_quantity
)
select distinct r.competition_id, 'round_runner_up', d.round_second_dp, null, 0
from public.competition_round_reward_rules r
cross join public.league_economy_defaults d
where r.role = 'participation'
  and d.id = true
on conflict (competition_id, role) do nothing;


-- ---------------------------------------------------------
-- 5. settle_round_rewards_v2 - rewritten for the 3-tier design.
--    Idempotency guarantee is unchanged (partial unique index +
--    exists() pre-check per role, exactly as before) - only WHO
--    qualifies for which role has changed.
-- ---------------------------------------------------------

create or replace function public.settle_round_rewards_v2(
  target_competition_id uuid,
  target_round_number integer
)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  incomplete_count integer;
  match_count integer;
  participant record;
  rule_row public.competition_round_reward_rules%rowtype;
  new_balance integer;
  new_tx_id uuid;
  new_grant_id uuid;
  grants_created integer := 0;
begin
  perform pg_advisory_xact_lock(
    hashtext('competition_round_settlement_' || target_competition_id::text || '_' || target_round_number::text)
  );

  select count(*) into match_count
  from public.matches
  where competition_id = target_competition_id
    and round_number = target_round_number;

  if match_count = 0 then
    return 0;
  end if;

  select count(*) into incomplete_count
  from public.matches
  where competition_id = target_competition_id
    and round_number = target_round_number
    and status <> 'completed';

  if incomplete_count > 0 then
    return 0;
  end if;

  if not exists (
    select 1 from public.competition_round_reward_rules
    where competition_id = target_competition_id
  ) then
    perform public.install_default_round_rewards_v2(target_competition_id);
  end if;

  -- ---- participation (universal "round completion" reward): every
  -- player registered in the competition, NOT only the players who
  -- happened to have a match this specific round_number. A 3-player
  -- round-robin always has exactly one bye per round (see this
  -- migration's header) - the bye player still "completes the
  -- round" and must still get this reward, per the approved
  -- baseline's own round-payout example (all three placements show
  -- the same 250 Round DP).
  for participant in
    select cp.profile_id
    from public.competition_players cp
    where cp.competition_id = target_competition_id
  loop
    if exists (
      select 1 from public.competition_round_reward_grants
      where competition_id = target_competition_id
        and round_number = target_round_number
        and profile_id = participant.profile_id
        and reward_role = 'participation'
        and status = 'granted'
    ) then
      continue;
    end if;

    select * into rule_row
    from public.competition_round_reward_rules
    where competition_id = target_competition_id and role = 'participation';

    if not found then
      continue;
    end if;

    new_tx_id := null;

    insert into public.competition_round_reward_grants (
      competition_id, round_number, profile_id, reward_role,
      duel_points_granted, voucher_type, voucher_quantity, status
    ) values (
      target_competition_id, target_round_number, participant.profile_id, 'participation',
      rule_row.duel_points, rule_row.voucher_type, rule_row.voucher_quantity, 'granted'
    )
    returning id into new_grant_id;

    grants_created := grants_created + 1;

    if rule_row.duel_points > 0 then
      update public.profiles
      set duel_points = duel_points + rule_row.duel_points, updated_at = now()
      where id = participant.profile_id
      returning duel_points into new_balance;

      insert into public.duel_point_transactions (
        profile_id, amount, balance_after, reason, metadata
      ) values (
        participant.profile_id, rule_row.duel_points, new_balance, 'round_participation',
        jsonb_build_object(
          'competition_id', target_competition_id,
          'round_number', target_round_number,
          'grant_id', new_grant_id
        )
      )
      returning id into new_tx_id;

      update public.competition_round_reward_grants
      set duel_point_transaction_id = new_tx_id
      where id = new_grant_id;
    end if;

    if rule_row.voucher_type is not null and rule_row.voucher_quantity > 0 then
      insert into public.reward_vouchers (
        profile_id, voucher_type, quantity, source_type, source_id
      ) values (
        participant.profile_id, rule_row.voucher_type, rule_row.voucher_quantity,
        'round_reward', target_competition_id
      );
    end if;
  end loop;

  -- ---- round_winner (1st place): the winner of each individual
  -- match played this round_number.
  for participant in
    select distinct winner_id as profile_id
    from public.matches
    where competition_id = target_competition_id
      and round_number = target_round_number
      and winner_id is not null
  loop
    if exists (
      select 1 from public.competition_round_reward_grants
      where competition_id = target_competition_id
        and round_number = target_round_number
        and profile_id = participant.profile_id
        and reward_role = 'round_winner'
        and status = 'granted'
    ) then
      continue;
    end if;

    select * into rule_row
    from public.competition_round_reward_rules
    where competition_id = target_competition_id and role = 'round_winner';

    if not found then
      continue;
    end if;

    new_tx_id := null;

    insert into public.competition_round_reward_grants (
      competition_id, round_number, profile_id, reward_role,
      duel_points_granted, voucher_type, voucher_quantity, status
    ) values (
      target_competition_id, target_round_number, participant.profile_id, 'round_winner',
      rule_row.duel_points, rule_row.voucher_type, rule_row.voucher_quantity, 'granted'
    )
    returning id into new_grant_id;

    grants_created := grants_created + 1;

    if rule_row.duel_points > 0 then
      update public.profiles
      set duel_points = duel_points + rule_row.duel_points, updated_at = now()
      where id = participant.profile_id
      returning duel_points into new_balance;

      insert into public.duel_point_transactions (
        profile_id, amount, balance_after, reason, metadata
      ) values (
        participant.profile_id, rule_row.duel_points, new_balance, 'round_winner_bonus',
        jsonb_build_object(
          'competition_id', target_competition_id,
          'round_number', target_round_number,
          'grant_id', new_grant_id
        )
      )
      returning id into new_tx_id;

      update public.competition_round_reward_grants
      set duel_point_transaction_id = new_tx_id
      where id = new_grant_id;
    end if;

    if rule_row.voucher_type is not null and rule_row.voucher_quantity > 0 then
      insert into public.reward_vouchers (
        profile_id, voucher_type, quantity, source_type, source_id
      ) values (
        participant.profile_id, rule_row.voucher_type, rule_row.voucher_quantity,
        'round_reward', target_competition_id
      );
    end if;
  end loop;

  -- ---- round_runner_up (2nd place, NEW): the loser of each
  -- individual completed match this round_number - the participant
  -- of that match who is not its winner_id. A player who did not
  -- play a match this round (the bye) is correctly never considered
  -- here - they only ever get 'participation' above, which is
  -- exactly the approved "3rd: no additional placement bonus."
  for participant in
    select distinct
      case when m.winner_id = m.player_one_id then m.player_two_id else m.player_one_id end as profile_id
    from public.matches m
    where m.competition_id = target_competition_id
      and m.round_number = target_round_number
      and m.winner_id is not null
  loop
    if exists (
      select 1 from public.competition_round_reward_grants
      where competition_id = target_competition_id
        and round_number = target_round_number
        and profile_id = participant.profile_id
        and reward_role = 'round_runner_up'
        and status = 'granted'
    ) then
      continue;
    end if;

    select * into rule_row
    from public.competition_round_reward_rules
    where competition_id = target_competition_id and role = 'round_runner_up';

    if not found then
      continue;
    end if;

    new_tx_id := null;

    insert into public.competition_round_reward_grants (
      competition_id, round_number, profile_id, reward_role,
      duel_points_granted, voucher_type, voucher_quantity, status
    ) values (
      target_competition_id, target_round_number, participant.profile_id, 'round_runner_up',
      rule_row.duel_points, rule_row.voucher_type, rule_row.voucher_quantity, 'granted'
    )
    returning id into new_grant_id;

    grants_created := grants_created + 1;

    if rule_row.duel_points > 0 then
      update public.profiles
      set duel_points = duel_points + rule_row.duel_points, updated_at = now()
      where id = participant.profile_id
      returning duel_points into new_balance;

      insert into public.duel_point_transactions (
        profile_id, amount, balance_after, reason, metadata
      ) values (
        participant.profile_id, rule_row.duel_points, new_balance, 'round_runner_up_bonus',
        jsonb_build_object(
          'competition_id', target_competition_id,
          'round_number', target_round_number,
          'grant_id', new_grant_id
        )
      )
      returning id into new_tx_id;

      update public.competition_round_reward_grants
      set duel_point_transaction_id = new_tx_id
      where id = new_grant_id;
    end if;

    if rule_row.voucher_type is not null and rule_row.voucher_quantity > 0 then
      insert into public.reward_vouchers (
        profile_id, voucher_type, quantity, source_type, source_id
      ) values (
        participant.profile_id, rule_row.voucher_type, rule_row.voucher_quantity,
        'round_reward', target_competition_id
      );
    end if;
  end loop;

  return grants_created;
end;
$function$;

revoke all on function public.settle_round_rewards_v2(uuid, integer) from public;
-- Intentionally NOT granted to authenticated - internal helper only,
-- called from within submit_competition_match_result_v2 (already
-- admin-gated). Unchanged from the prior version.

commit;
