-- =========================================================
-- APPLY FINAL SEASON 1 RARITY RECALIBRATION (engine 2026-09-01.1)
--
-- Materializes the already-approved 2026-09-01 rarity-engine
-- recalibration into card_catalog.game_rarity for the eligible
-- Duelist Circle Classic pool. Generated by
-- scripts/apply-final-season1-rarities.mjs from the 2026-08-25
-- full-catalog valuation snapshot (the only local snapshot
-- available; effect_text/live re-scoring was not possible in this
-- sandbox - see that script's header for the full methodology and
-- a flagged, known deviation: this recalibration yields 70
-- Legendary cards against the eligible pool used here, above the
-- ~25-35 go-live target. Root cause: generic low-dependency staples
-- with a maxed ceiling score clear legendaryGate Path B; several of
-- them carry a suggested_release_stage of 2 in the source valuation
-- data (i.e. this project's own oppressiveness review already
-- recommended holding them back from stage 1), but
-- card_catalog.release_stage has never been populated by any
-- committed migration, so that recommendation could not be applied
-- here without changing what counts as "eligible" - out of scope
-- for this migration per its own directive. Flag for operator
-- review before/at go-live.
--
-- Does NOT touch: card eligibility, format_card_overrides, Boss
-- Route tables/exclusivity, pack odds, economy config, or any of
-- the 15 manually-overridden cards from
-- 202608301000_seed_manual_rarity_overrides.sql and
-- 202608301100_seed_manual_rarity_overrides_round2.sql (excluded
-- from this file entirely - those hard overrides stand as already
-- committed).
--
-- Idempotent: every statement is a plain UPDATE ... WHERE id = ...
-- keyed on card_catalog_id (safe to re-run; a re-run after this
-- migration already applied is a no-op).
-- =========================================================

begin;

update public.card_catalog set game_rarity = 'Secret Rare' where id = '00036f96-1af0-486c-9c86-b314481f7769'; -- Koa''ki Meiru Sandman: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '01fe4c96-2926-4ae7-bf7a-022a4b243b9f'; -- Alich, Malebranche of the Burning Abyss: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '04d77e8a-66a6-4bb3-bc13-d1f8848373c0'; -- Ultimate Obedient Fiend: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '0519a3a6-942e-4a4b-9da1-ecb260bad808'; -- Number 99: Utopic Dragon: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '059ada0c-ba04-409a-aebc-2b8170178046'; -- Evilswarm Ophion: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '0614a4d0-5254-4368-b90a-2461d5ec4235'; -- Garlandolf, King of Destruction: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '06333e1c-7f97-4188-8cca-d3f0406d0728'; -- Koa''ki Meiru Wall: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '068d6a5d-9d40-4e3b-8a0a-43f3b7d4fa49'; -- Totem Bird: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = '0bee3673-dbf2-46d0-a77b-3c464de6fe43'; -- Shark Fortress: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '0c3a2f8c-6a53-4afa-9bff-c03f88bdda1f'; -- Mechquipped Angineer: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = '0deba7b7-07fb-45a3-ab99-302ff687820c'; -- Evigishki Merrowgeist: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = '11838443-57a6-4e33-a96f-becd90dfec01'; -- Number 80: Rhapsody in Berserk: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Rare' where id = '125004e7-7e21-4157-a04b-4523d620628f'; -- Ghostrick Socuteboss: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '132b1d79-f5fa-4556-b6b5-4b44728af70b'; -- Gagagadraw: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '13615606-d51b-41bf-95d3-2371f50e346d'; -- Leviair the Sea Dragon: Rare -> Normal
update public.card_catalog set game_rarity = 'Ultra Rare' where id = '13d10a9d-ee64-40cd-8d4f-a12233781760'; -- Photon Strike Bounzer: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '13d82a2b-2335-423d-8654-e89c69999522'; -- Vennominaga the Deity of Poisonous Snakes: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '14f24dde-fc6e-4b95-ab48-117e09e92918'; -- CXyz Mechquipped Djinn Angeneral: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '1588879e-6802-4870-9151-66219487128f'; -- Obelisk the Tormentor: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '17de8830-80e9-4e50-9130-186325c4d6f3'; -- Gryphon Wing: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '183511d7-87ca-4a06-9114-54779b8ec041'; -- Night Papilloperative: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '184cd0ee-c102-4b74-8417-d9a161a47f87'; -- Strike of the Monarchs: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '1983c128-cf5a-469a-8e74-9f608611ed0b'; -- Number 53: Heart-eartH: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '19988b0b-ab2d-4fd6-b309-42ceace61b67'; -- Advance Zone: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '19ed54bd-8844-47fa-9c66-46bcc0b69c53'; -- Lavalval Chain: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '1a03ec3b-9a14-4ab7-a812-ee6b0643ccb1'; -- Number C9: Chaos Dyson Sphere: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '1ad81d90-c7fe-4a8e-9550-a19bff7ccd68'; -- Neos Wiseman: Ultra Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '1c56331c-2855-493f-a810-dd7ef344c433'; -- Fire King High Avatar Garunix: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '1ec3e881-3ee4-4890-8f43-990bfc9e9a8e'; -- Tri-Edge Levia: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '1f006146-f16c-464f-85d3-20449d3a13c8'; -- Starliege Paladynamo: Ultra Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '1fa5aa80-5161-46d4-885b-e352e1db9be4'; -- Hamon, Lord of Striking Thunder: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '20b3565a-18fc-47b4-a982-1c5fc3e6b3fe'; -- Vanity''s Call: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '21aaa42e-6503-4337-813c-29233685e9c7'; -- Dante, Traveler of the Burning Abyss: Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '23d63565-4815-4064-8477-71c3a8e4f740'; -- Number 102: Star Seraph Sentry: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '2558b530-bd53-47d5-a127-246567e39f4f'; -- Moisture Creature: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '286927b1-a243-4b69-ae54-8cf770d586f2'; -- The Huge Revolution is Over: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '2875f997-dbe4-4532-9d81-ec0eab85eff0'; -- Number 74: Master of Blades: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '2894c395-445e-46a4-95fc-024f579741be'; -- Armoroid: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '28b49c2c-179d-4f36-90df-0568f0627a88'; -- Ancient Gear Beast: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '29406d81-7d71-480b-9687-f69123915780'; -- Elemental HERO Thunder Giant: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Super Rare' where id = '29485306-4ba3-4611-b78c-063246ceaf38'; -- Stellarknight Delteros: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Normal' where id = '29dd1c7b-b8ab-4c9f-8110-d2ef71f41feb'; -- XY-Dragon Cannon: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '2a5861a3-2b7e-4f07-bf77-79286c078d58'; -- Dark Nephthys: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '2b39143b-877a-4209-bb42-8659d7253681'; -- Unformed Void: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '2b7415cc-3b36-4b92-910d-be3a94cbe5a7'; -- Number 54: Lion Heart: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = '2b9d7d0b-fa68-47aa-885b-f1883801793f'; -- Elemental HERO Shining Phoenix Enforcer: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '2bcd339d-d988-4b44-940c-df371ef93ef2'; -- Dark Simorgh: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '2c6ceed8-956b-447e-88b7-feea13572465'; -- Battlin'' Boxer Cheat Commissioner: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '2f24c4e5-d8c2-4037-a655-f08b4694c988'; -- High Priestess of Prophecy: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '2ff3b125-4448-4948-a780-93238f86c78f'; -- XZ-Tank Cannon: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '309ca729-a1e4-4c33-acf0-615301387601'; -- Levia-Dragon - Daedalus: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '30ed2423-a1e5-4801-bc16-62797d4d5e4e'; -- Number 69: Heraldry Crest: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '31712c2a-c9f2-4f30-ac3c-d95c068d4f81'; -- Fenghuang: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '318e826c-fd5b-475c-b830-0fd36752a852'; -- Assault Revival: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '32e8663e-a64f-4c28-8a1b-4de426d0d8f1'; -- Number 58: Burner Visor: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = '354d2f51-2d73-4c30-9845-ff0e36cc87f7'; -- Elemental HERO Dark Neos: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '356797dc-41b0-4fea-b7ec-19326051336d'; -- Genex Ally Reliever: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '35d7c737-e6e0-43cb-8561-5e28c0b594f0'; -- The Winged Dragon of Ra: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '376318c0-e1e3-41f5-ba72-632945d55b4c'; -- Gishki Emilia: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '38f4e867-ec99-42a0-b253-a09c920b1733'; -- Black Ray Lancer: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '39317eaa-86b2-4854-862c-9e16cbb7c850'; -- The Resolute Meklord Army: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '39fee178-e2af-44e8-8b4f-d12890624d19'; -- Shining Elf: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '3ab32d75-8832-493f-b18c-19aea18b0fe1'; -- Prime Material Dragon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '3b754ad7-5702-4436-99b1-d6ab5e285177'; -- Number C101: Silent Honor DARK: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '3c4e1353-14c4-4507-b553-42dc569df93e'; -- Flamvell Counter: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '3d7878ea-2ce1-4932-88e7-375220a0952a'; -- Skill Drain: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '3dcd319f-e69b-4438-8e50-3b335101e45d'; -- Crimson Knight Vampire Bram: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = '3f980bfa-8e3a-44c2-a2b0-b90a209d3832'; -- Number 11: Big Eye: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '401c2c7c-3458-46e5-8faf-c16f976684a0'; -- Dark Dust Spirit: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '41e3b32b-f94d-4a29-938e-592c9d3b42de'; -- Superdreadnought Rail Cannon Gustav Max: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '439214a6-aab8-4e3e-bb9e-a6df6c0cb810'; -- Ice Queen: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '441261d5-681b-4531-97bf-7aae5b07b31f'; -- El Shaddoll Shekhinaga: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '44cea99d-d71c-4b69-9a95-16e0058c3dcf'; -- Blaster, Dragon Ruler of Infernos: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4527b9c0-ae93-425b-84db-730091454c95'; -- The Seal of Orichalcos: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '462f73ba-f471-486d-8eb9-6e9ea965ff5f'; -- Number 10: Illumiknight: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = '46689f70-cd6b-4fb4-b0c7-6404f438ee53'; -- Gem-Knight Pearl: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '46b9807e-065b-4c7a-9917-184bbb6c18c3'; -- Darklord Zerato: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '47a8aaa6-7b20-4f07-b29b-6042d5cea5b1'; -- Dark Armed Dragon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4814f01d-8b1d-465c-a179-af57a33cb65d'; -- Aratama: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '48b5565f-5b21-4ef4-8151-bfbf443fae71'; -- Redox, Dragon Ruler of Boulders: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '49b8c56d-003a-4ed9-b288-658de1d9e8d5'; -- Yaksha: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '49e42582-8416-4024-a6f1-57d116834d41'; -- Dark Ruler Ha Des: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '4a808eab-51b7-41b9-8c41-f9546d34859e'; -- Superalloy Beast Raptinus: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4ab46706-2a83-483b-937a-684fdc298333'; -- Mosaic Manticore: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4c252dfc-1df2-4529-b184-14d202b62017'; -- Gorgon''s Eye: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4e5b4045-47f2-4f90-b2e3-a9225667d9e6'; -- Rasetsu: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = '4e5b9ac0-3ce2-493c-979e-0804e5a82785'; -- Coach King Giantrainer: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '4e7a0b77-ae8b-43b7-a49a-41cc637d76bd'; -- Dark Magician of Chaos: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '4ec55483-41cd-48cb-a19f-759feb42672a'; -- Jowgen the Spiritualist: Ultra Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '5125d328-9b3a-4e74-9ddd-a44e913b1d5c'; -- Elemental HERO Wild Wingman: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '51af209a-685c-4e0d-ad5c-bbb0249b125b'; -- Phoenix Gearfried: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '534549fc-aa82-472f-8eb2-bae51e60d643'; -- Black and White Wave: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '547b92c8-0615-4c31-a315-8ca3ff87a0f6'; -- Ancient Gear Gadjiltron Dragon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '54ceef64-dd76-4ba8-a881-518f5abd2313'; -- Gachi Gachi Gantetsu: Rare -> Normal
update public.card_catalog set game_rarity = 'Super Rare' where id = '54f3b759-bacb-4661-9cd5-c2e4e197d357'; -- Artifact Durendal: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '563c8be9-6105-48a1-95ef-dc58cdf59b91'; -- D.D. Esper Star Sparrow: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '58ab010d-86f2-4e2f-abd6-e3af18011e5d'; -- Rocket Arrow Express: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '5a2c5baf-6201-4985-9eb7-72a7f9b310f9'; -- Gaia Dragon, the Thunder Charger: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '5a67fcd0-8b70-47db-93c7-9567ae7ed814'; -- Prime Material Falcon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '5ba62161-1fe1-442a-adb3-68664af5c589'; -- Blackwing - Aurora the Northern Lights: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Ultra Rare' where id = '5bcb177a-fe05-438c-ab60-b9f98de6bd0c'; -- First of the Dragons: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Normal' where id = '5c442f48-5e77-4376-b490-5339c4fe9dbe'; -- Number 44: Sky Pegasus: Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '5cab27a5-e93b-4f31-8324-4a7a0fa18303'; -- Anti Raigeki: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '5d08a256-3cde-4f0c-87b8-285de5cb7a6a'; -- Barbaroid, the Ultimate Battle Machine: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '5f5b26cd-edce-4dd1-905f-be6899a7a224'; -- Cards for Black Feathers: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '6061e8a3-169f-4fe9-b231-8c20fc80f6ad'; -- Number 83: Galaxy Queen: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '60c10f7e-dead-4500-ab8a-81d81ffbce80'; -- Sacred Sword of Seven Stars: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '61918f2c-37de-4dba-8ba2-d080e848ee6a'; -- Gladiator Beast Darius: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '639bdc1b-d9aa-4453-b1a1-fa2cf9908846'; -- Chaos Ancient Gear Giant: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '63d723f3-ad8b-486b-b14a-009d9d9705ce'; -- Cyber Dragon Nova: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = '63f52f68-7d80-4767-a7a2-24b31ccec9c1'; -- Number 30: Acid Golem of Destruction: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '64924d95-3307-4ab7-84c8-f52361ab1303'; -- Shining Silver Force: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '64bd02a5-871e-41ec-94f9-5f946b90c749'; -- Fushioh Richie: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '651c9ef3-0c10-498d-90c2-1bac9dd13d62'; -- Number 72: Shogi Rook: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = '66a00fa6-b6be-4bdc-80a7-8cb8bbaecb4f'; -- Abyss Dweller: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '66f6b6c1-5021-4474-ac2f-593c2a896e62'; -- Darknight Parshath: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '6b52c536-cb65-4c5a-b962-439ab63642bf'; -- Mist Valley Apex Avian: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '6bdf97b9-e004-4ae8-9d9b-05348aa077b4'; -- Morphtronic Accelerator: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '6d77931c-fcfa-4487-b531-2208b20cda5f'; -- Hieratic Dragon King of Atum: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '6e57eb61-036f-4f45-a0a6-55b3efc547e6'; -- Superheavy Samurai Soulbreaker Armor: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '6e6cc2d8-7dac-4f69-9582-fe2986c54455'; -- M-X-Saber Invoker: Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '6ec8b2c0-3611-4910-acce-0adeae5070d2'; -- Blackwing - Abrolhos the Megaquake: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '6ecb77e7-1cf3-4b14-88a4-da4103935e04'; -- Shutendoji: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '77871f08-05da-49b8-87b1-860c38bd5d85'; -- Exodius the Ultimate Forbidden Lord: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '77dfaebe-036e-4e70-bd3c-f797eef7d4da'; -- Steelswarm Hercules: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '77e71e3d-35d3-455c-93d9-c2d3262b944c'; -- Battlecruiser Dianthus: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = '785c5b77-0207-4897-a49a-08cd4318ef91'; -- Number 82: Heartlandraco: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '7944d3d0-1f0d-4018-b3b3-09502625a44f'; -- Number 39: Utopia Roots: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = '7968fd40-d70c-4144-a9a4-22fa21f0e79f'; -- Elemental HERO Necroid Shaman: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '7aadf3e2-dd50-45f1-b8ed-7fd155e3d361'; -- CXyz Skypalace Babylon: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = '7adc4ecb-a7b9-4318-b877-1ad9a207c990'; -- Wind-Up Carrier Zenmaity: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = '7b9af4fa-d678-4025-8d23-035e0e6f348d'; -- Panzer Dragon: Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '7bcb46a1-52e9-4a11-80fc-ee6d23a97880'; -- Van''Dalgyon the Dark Dragon Lord: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '7bdf92e5-2cfc-4872-8624-14c6108e66a9'; -- Red Dragon Ninja: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '7c4884bd-8fca-49f9-9eae-e1abd65d9440'; -- King of the Feral Imps: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '7ce09631-1a11-4bd2-80db-20134599dc88'; -- Tempest, Dragon Ruler of Storms: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '7e5b613e-3d5a-4d97-99a1-085edce81d5f'; -- Dark Magician Knight: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '7e7e47d2-a866-4547-8b7f-dabb24de323a'; -- Witch of the Black Rose: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '7ec21799-fa0b-4ef0-a325-f766432ee399'; -- Metaion, the Timelord: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '8037dc8c-88ba-40e0-9c43-4f9e81d72213'; -- Nikitama: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = '845c35a0-649f-46ea-8a3f-1f3582089860'; -- Noble Knight Eachtar: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '84bc4321-d683-45b8-bf4f-90caacbc446d'; -- Wind-Up Arsenal Zenmaioh: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = '85dd91a4-c418-4092-a8b1-816633f7d8b8'; -- Elemental HERO Tempest: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '875ba867-349c-41dc-b6d7-276cae77f1f0'; -- Rebound: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '87bfca8f-d30f-4c35-8168-be68164d1548'; -- Maestroke the Symphony Djinn: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = '888c348a-106b-436a-b10b-fab18ae23433'; -- Number C6: Chronomaly Chaos Atlandis: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '8932bf80-39f6-488c-81ce-48f5eb4481fb'; -- Rosaria, the Stately Fallen Angel: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '899a8bf2-ad0f-4910-9cb2-8030189a5e73'; -- Lavalval Ignis: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '8b163ae2-f3fb-42a7-9131-9ec9c12ac1c6'; -- Reign-Beaux, Overlord of Dark World: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '8b511cfc-ea1c-458d-8f34-1d1ad86613c8'; -- Armed Dragon LV7: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '8c8774a1-eb57-4455-b5a8-862d838baa32'; -- Chow Chow Chan: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '8e29b53a-ba45-4c48-9ac7-8413d065230f'; -- Vylon Matter: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '8e40ebfd-65c3-4d3c-8cc0-0f4174419f34'; -- Number 20: Giga-Brilliant: Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = '8e7762ce-a2f6-4e27-974c-380f861878b2'; -- Cyber Network: Ultra Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = '91da51ce-8929-4b52-a9d1-d029eea41ac8'; -- Grenosaurus: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = '922e87fa-930a-4ae4-b5a4-da30a67e8dd3'; -- Number 46: Dragluon: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '9274cdaf-ff22-4e79-acc0-5d39746b1cfd'; -- Fishborg Archer: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '930a8a07-e616-4a91-b226-4b3b0056af9e'; -- Dark Lucius LV8: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '9349fd9b-e4db-49f9-b94a-411f2c43734c'; -- Gemini Imps: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = '956e8b60-7659-4c3d-8f0a-3eca9e0fdead'; -- Number C39: Utopia Ray V: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '984285f7-49fe-412c-8db7-6faebc537472'; -- Stand-Off: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Ultra Rare' where id = '9882b3e6-c064-43e7-ac62-dc51901745b7'; -- Divine Dragon Knight Felgrand: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Legendary' where id = '9905bba4-4380-422a-9e01-944c18e71181'; -- Darkness Neosphere: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = '9beec0ab-d21e-4ff4-8c37-592e80d6bf42'; -- Armored Glass: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = '9e1e4425-6dab-458b-9a9b-5b4969dfebe7'; -- Number 42: Galaxy Tomahawk: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = '9eb40e0a-d3aa-4c2a-9d35-d0aec8b240a8'; -- Diamond Dire Wolf: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = '9f0e1ae9-ee14-42a2-8182-42317fbe7760'; -- Debunk: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '9f9184dc-74ae-4aa0-9ef9-840a43e4cdba'; -- Number C105: Battlin'' Boxer Comet Cestus: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = '9fabb5c5-ab2f-4029-8504-42069e05cf1a'; -- Hieratic Dragon of Sutekh: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = '9fd60f25-9900-4f7e-9c61-6071ceb36e6f'; -- Chronomaly Crystal Chrononaut: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = 'a02bd061-c73d-4cb0-9e76-891fb68cee7c'; -- Number 9: Dyson Sphere: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'a2530b8e-a77e-44e8-9941-7d5e6c0ffd4a'; -- Yubel - Terror Incarnate: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'a2ddeb9d-d260-4585-880a-f90143a2310f'; -- The Monarchs Erupt: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'a30abb67-2c71-4926-887b-40b30b32d4ea'; -- Wind-Up Zenmaines: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'a4f1901e-f2b7-444d-a036-46c46e37942c'; -- Earthbound Immortal Ccarayhua: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'a71f4fd5-9092-44e6-a429-a67728bfa1cc'; -- Kinka-byo: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = 'a80810d9-800d-49da-8c42-767a7063ff71'; -- Number C106: Giant Red Hand: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'a9027bc0-3ee5-4ad3-8cf9-4c849dd1f327'; -- Dark Master - Zorc: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'a9442721-3a09-4006-9303-2db0cb55bd8b'; -- Brain Golem: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'aab5a9dc-e54c-4d66-adc1-ef339412d4d0'; -- Skull Archfiend of Lightning: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = 'abe34f76-9d8c-4a0b-8770-19449d3f8637'; -- Slacker Magician: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'ac49119e-21b9-454b-a20f-2b41f520143e'; -- XYZ-Dragon Cannon: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = 'adb7b898-a573-49f3-86ae-4e85f9d2bdd3'; -- Number 91: Thunder Spark Dragon: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'ae16322b-3522-41dd-a9c5-adce47b02f1d'; -- Burgeoning Whirlflame: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'aea3ce12-55a0-428e-b830-e230ed9be682'; -- Darkstorm Dragon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'aecd72aa-355e-4f8b-8d1c-e658793ef3ff'; -- Koa''ki Meiru Hydro Barrier: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = 'b0c71001-d128-4ccf-bae8-62bd60c13947'; -- Dark Rebellion Xyz Dragon: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'b1e2e443-cc64-4b0c-a14a-d96b826af425'; -- Soul Drain Dragon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'b2002090-2bec-4772-a0d8-2baae41f37d3'; -- Number C88: Gimmick Puppet Disaster Leo: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'b34fbe40-6bd2-4af7-a0fa-38d96282d576'; -- Master Hyperion: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'b3a671f6-233d-4a01-b19e-2567cbb8fc66'; -- Submersible Carrier Aero Shark: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'b42a8d6d-41de-4eac-9573-5829a5688157'; -- Number 19: Freezadon: Rare -> Normal
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'b4f7a981-1ac1-483a-9e3b-5b02bedbee1a'; -- Gladiator Beast Heraklinos: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'b50ad0e0-3a38-40d2-b24b-94d1c6140c30'; -- Jurrac Titano: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = 'b5c64423-baf1-4ec8-bac2-6f049dede2aa'; -- Madolche Tea Break: Ultra Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'b6586b22-4119-4c41-9f84-8f43193ffd71'; -- Future Samurai: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'b6e69927-8760-400f-b4c1-87a2c5e576b7'; -- Fossil Dyna Pachycephalo: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = 'b7897f3f-51db-4fcf-95fc-6413d3d16ffd'; -- Elemental HERO Darkbright: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'b8da3dea-cd5d-43ad-9bab-e9a1fb0bf099'; -- Silent Swordsman LV7: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'b95fe251-4c75-4c5d-bf80-fa9cd17752c4'; -- Superheavy Samurai Soulbang Cannon: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'ba125248-41af-45b2-8230-0bd587e2cad9'; -- Cards from the Sky: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'bc1c9799-644b-4bea-aeb0-51b82f4ce4c7'; -- Bujincident: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'bd24e751-5bf3-4017-b66c-52bc6e726fba'; -- Tackle Crusader: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'bdc5a7f7-50a2-4159-80c1-fc7cc0be32e3'; -- Final Inzektion: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'bdd6dcbd-833a-43fb-9a53-3523ed2bf819'; -- Rainbow Neos: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'c0d7ad1e-7287-4d6f-b1a5-f78e672a8109'; -- Shark Caesar: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'c16e29c9-401c-44ae-ae4c-f46ddcdf4b4d'; -- Number C15: Gimmick Puppet Giant Hunter: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'c27fee25-086f-4864-9f7d-f03bba84e382'; -- Rainbow Dark Dragon: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'c2ec6984-2ddd-46f6-8f2e-facb5d195f8e'; -- Destiny End Dragoon: Legendary -> Ultra Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'c31f2e85-022c-4c28-9c5d-d92f9cfdef5f'; -- Temtempo the Percussion Djinn: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'c4a006c7-67de-4529-88af-b0aeef9d0a70'; -- Gladiator Beast Nerokius: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'c4e7b6f2-73e8-4bbd-b82e-88247ae0a759'; -- Number 32: Shark Drake: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'c548209c-d542-49c0-ae0d-859ab9090989'; -- Steelswarm Caucastag: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'c6784654-2290-443b-b8ee-c3387119cb67'; -- Cyber Blader: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'c8639c59-4db2-4cef-8d90-34d336c23a34'; -- Judgment of the Pharaoh: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'c9379ec8-ebe7-4ba9-be69-ae27afb9383a'; -- Mermail Abyssgaios: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'c9ad87c4-8c7c-4f6d-bdd4-977af4bdc30f'; -- Allure of Darkness: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'c9d2c49f-f557-450e-a182-fec4a5f0cd43'; -- Brotherhood of the Fire Fist - Lion Emperor: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'c9fd4dea-8469-4427-aff8-889e0c5dc4b6'; -- Gagagigo the Risen: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'ca816eb9-22a8-42b8-bdfb-baa7c71e20a7'; -- Morphtronic Forcefield: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'cace294a-0ab2-499a-ab8d-66ecd1d4d72f'; -- Evil HERO Wild Cyclone: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'cd18b7c9-d9d1-4a9f-a9b8-1cb5d19fbb88'; -- Ghostrick Dullahan: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'cf117ee3-7bc7-4fcd-a080-94780ae98180'; -- Muzurhythm the String Djinn: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'd0ab4d98-e6b0-4ea8-8046-47a66f9dc2ee'; -- Tin Archduke: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'd15c2406-52eb-4ea2-b4a7-656600c89ee1'; -- Elemental HERO Shining Flare Wingman: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'd1b68d27-b482-4454-9920-c813449c7606'; -- Adreus, Keeper of Armageddon: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'd2f30116-dc9d-4d62-ad23-195b4ad95eb8'; -- Number 17: Leviathan Dragon: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'd42e02f5-fced-412e-b99c-a1ece65b0675'; -- Evolzar Dolkka: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'd43c4266-99c0-47db-a7ce-c3a79c0ca469'; -- Stardust Dragon/Assault Mode: Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'd4705ec6-3cde-4ed7-b1b9-8afec4a62a84'; -- Stellarnova Alpha: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = 'd5bd6066-3d9c-4f03-986a-5afe43b51752'; -- Zubaba General: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'd611e5db-6ae0-4c34-adc3-dc0bf12d6126'; -- Ancient Gear Engineer: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'd64ea2ab-32c3-4ee5-9da7-76a67bd7b72d'; -- Elemental HERO Plasma Vice: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'd67d6657-97a2-4a4e-8fcb-9f107df1a4fd'; -- Black Luster Soldier - Envoy of the Beginning: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'd78538d9-b0f4-40c0-bc8b-ddffaaebcd17'; -- Gauntlet Launcher: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'd98790b4-f8a5-43ed-ac43-3623208a7499'; -- Herald of Ultimateness: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'db42ffe4-f33f-43f8-a6e5-719026a6bff2'; -- Ghost Reaper & Winter Cherries: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Ultra Rare' where id = 'db431a0f-d934-4806-af84-3d12024abe7d'; -- Arcana Knight Joker: Secret Rare -> Ultra Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'dba886d6-331a-4366-9a97-e63cb4a45647'; -- Number 48: Shadow Lich: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'dca30b76-d5d0-4dac-9a24-5ed463f8b78f'; -- My Body as a Shield: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'dcf05b44-e9f6-47dd-9a7e-1017106703f7'; -- Madolche Chickolates: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'ddc0bf38-26d3-40df-b835-b00b419efba5'; -- Elemental HERO Magma Neos: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Legendary' where id = 'ddc183ed-0c16-44b1-8ada-cac66609bc94'; -- Ancient City - Rainbow Ruins: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Legendary' where id = 'de61e6c7-a103-4128-ab54-81747b9902da'; -- Blue-Eyes Shining Dragon: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = 'deecacee-666c-4677-9dcb-cc00b32ddbe9'; -- Sword Breaker: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'df5ec882-ad86-43d4-b51c-3ef98782cb84'; -- Baby Tiragon: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'e0434ae7-e0d6-4b3b-bc75-d97f2e4dd215'; -- Number 66: Master Key Beetle: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'e456326a-9b1d-4c4b-9c35-729808655d5f'; -- Number 65: Djinn Buster: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'e6b7ddad-5644-43bd-a011-8e349be2769f'; -- Naturia Exterio: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Super Rare' where id = 'e6b8c7c4-c6db-47d3-80f7-b5178076eb0e'; -- Orea, the Sylvan High Arbiter: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'e6be4500-5e09-4b15-a99a-8a81992df9fe'; -- Moon Dance Ritual: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = 'e72737c1-4a96-47ca-b0ae-0edeb4fc8359'; -- Stellarknight Triverr: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'e77b63af-2901-4898-af77-4505841f68b2'; -- Evolzar Solda: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'e7c2f78a-db39-494a-842b-c271c8899742'; -- Vennominon the King of Poisonous Snakes: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'e8307779-071e-45c0-89a9-5c8267ff28a7'; -- YZ-Tank Dragon: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'e8406162-3eb6-4b3a-9e2f-8c822ef7c4e8'; -- Fairy Cheer Girl: Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'e9f5a3f4-6b08-4d54-91e2-923a18fa4d88'; -- Dark Paladin: Ultra Rare -> Normal
update public.card_catalog set game_rarity = 'Normal' where id = 'ee60e442-241e-49eb-aa6e-835296a3bc04'; -- Steelswarm Roach: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'ee7d46e5-6f50-4635-9e02-96748437001e'; -- Archlord Kristya: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Rare' where id = 'efb3467c-418b-439e-8fea-cc1fe49adbfb'; -- Vylon Disigma: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'f06ad49f-0ce5-4b8b-b664-0c3581df12cc'; -- Black Luster Soldier - Envoy of the Evening Twilight: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Normal' where id = 'f0dcf7ef-ec78-4615-8f5c-29cf16b067d3'; -- Photon Papilloperative: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'f145dafd-2812-449e-b838-0e85bfce8ffa'; -- Cursed Seal of the Forbidden Spell: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'f2cc105b-8dc4-422c-a0e0-d37ce28fc15b'; -- Windrose the Elemental Lord: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Legendary' where id = 'f31f8143-af5e-4619-87aa-4d14d877b85c'; -- Darklord Asmodeus: Secret Rare -> Legendary
update public.card_catalog set game_rarity = 'Rare' where id = 'f3d9e9d7-46d4-481f-812f-297b3a02df61'; -- One-Eyed Skill Gainer: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Rare' where id = 'f3f2f9e3-b19b-4200-9a1c-9d0e1944334b'; -- Number 61: Volcasaurus: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'f53983ac-2a8a-41a4-a06f-66115adaff43'; -- Number 34: Terror-Byte: Rare -> Normal
update public.card_catalog set game_rarity = 'Rare' where id = 'f608361e-18e5-4dee-b896-f085d4421018'; -- Number C32: Shark Drake Veiss: Super Rare -> Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'f683021e-ad13-4b29-bc69-2331cf85e088'; -- Ice Beast Zerofyne: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'f87ce6e2-8359-49f8-940a-1183887eae69'; -- Kachi Kochi Dragon: Rare -> Normal
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'f8d55751-b079-4858-8a25-e3da7d18a87e'; -- World of Prophecy: Ultra Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Super Rare' where id = 'fbf356af-6ab2-4fff-9307-f08b977aca3c'; -- CXyz Dark Fairy Cheer Girl: Ultra Rare -> Super Rare
update public.card_catalog set game_rarity = 'Secret Rare' where id = 'fcc9d8d2-9421-49fe-b70a-2a349442a100'; -- Exodia Necross: Super Rare -> Secret Rare
update public.card_catalog set game_rarity = 'Normal' where id = 'fe981c65-509d-4cee-b585-224e2b2dd154'; -- Daigusto Phoenix: Rare -> Normal

commit;
